# Site settings
timezone: Europe/Berlin

#baseurl: '/tolosalaroja/' # the subpath of your site, e.g. /blog/
#url: 'https://toulouserepublicana.github.io/' # the base hostname & protocol for your site

#url: 'http://toulouserepublicana.com'
url: 'https://toulouserepublicana.github.io' 

title: 'Tour Toulouse Republicano'
author: 'Elisa Vílches'

languages: [ 'es', 'ca', 'fr']

google_font_sans_serif: 'Source+Sans+Pro:300'

default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: es
      description: 'Tour del exilio republicano español en Toulouse.'
  - scope:
      path: 'fr'
    values:
      lang: fr
      description: 'Tour del exilio republicano español en Toulouse.'
  - scope:
      path: 'ca'
    values:
      lang: ca

# CSS Minification
sass:
  style: compressed

