# Site settings
timezone: Europe/Berlin

# Comment these out for development
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://www.tour.toulouserepublicana.com/'  # the base hostname & protocol for your site

title: 'Tour Toulouse Republicana'
author: 'Elisa Vílches'

languages: [ 'es', 'ca', 'fr' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: es
      description: 'Tour del exilio republicano español en Toulouse.'
  - scope:
      path: 'fr'
    values:
      lang: fr
      description: 'Tour del exilio republicano español en Toulouse.'
  - scope:
      path: 'ca'
    values:
      lang: ca
  - scope:
      path: 'es'
    values:
      lang: es

# CSS Minification
sass:
  style: compressed

